language: go
go:
 - "1.10.x"

sudo: required
install:
 - bash ./tools/devenv/install-go-tools.sh
 - gx install --global

script:
 - diff -au <(gofmt -s -d ./pkg) <(printf "")
 - go test -race -v ./...
 - go test -race -v -covermode=atomic -coverprofile=coverage.out ./pkg/...
 - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
