language: go
go:
 - "1.10.x"

sudo: required
install:
 - bash ./tools/devenv/install-go-tools.sh
 - gx install --global

script:
 - diff -au <(gofmt -d ./pkg) <(printf "")
 - go test -race -v ./pkg/...
 - go test -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
